name: MyGame

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: SDK
        uses: android-actions/setup-android@v3

      - name: Licences
        run: yes | sdkmanager --licenses

      - name: Install
        run: sdkmanager "ndk;26.3.11579264"

      - name: Build
        working-directory: Platform/Android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Rename
        run: mv Platform/Android/app/build/outputs/apk/release/app-release.apk MyGame-Android-${{ github.ref_name }}.apk

      - name: Release
        uses: softprop/action-gh-release@v2
        with:
          files: Platform/Android/app/build/outputs/apk/release/*.apk

  windows:
    runs-on: windows-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: CMake
        run: >
         cmake -S . -B build -G Ninja 
         -DCMAKE_C_COMPILER=clang
         -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Rename
      run: ren Executables\Windows\MyGame.exe MyGame-Windows-${{ github.ref_name }}.exe

      - name: Release
        uses: softprop/action-gh-release@v2
        with:
          files: Executables\Windows\MyGame-Windows-${{ github.ref_name }}.exe
        

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4
      
      - name: Clang
        run: sudo apt update && sudo apt install -y ninja-build clang cmake

      - name: CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      
      - name: Build
        run: cmake --build build

      - name: Rename
        run: mv Executables/Linux/MyGame Executables/Linux/MyGame-Linux-${{ github.ref_name }}

      - name: Release
        uses: softprop/action-gh-release@v2
        with:
          files: Executables/Linux/MyGame-Linux-${{ github.ref_name }}
      

  macos:
    runs-on: macos-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Ninja
        run: brew install ninja

      - name: CMake
        run: >
         cmake -S . -B build -G Ninja
         -DCMAKE_C_COMPILER=clang
         -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Rename
        run: mv Executables/MacOS/MyGame Executables/MacOS/MyGame-MacOS-${{ github.ref_name }}

      - name: Release
        uses: softprop/action-gh-release@v2
        with:
          files: Executables/MacOS/MyGame-MacOS-${{ github.ref_name }}