name: MyGame

on:
  push:
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: SDK
        uses: android-actions/setup-android@v3

      - name: Licences
        run: yes | sdkmanager --licenses

      - name: Install
        run: sdkmanager "ndk;26.3.11579264"

      - name: Build
        working-directory: Platform/Android
        run: ./gradlew assembleRelease

      - name: Android
        uses: actions/upload-artifact@v4
        with:
          name: MyGameAndroid

  windows:
    runs-on: windows-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: CMake
        run: >
         cmake -S . -B build -G Ninja 
         -DCMAKE_C_COMPILER=clang
         -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Windows
        uses: actions/upload-artifact@v4
        with:
          name: MyGameWin32
          path: Executables/Windows

      - name: Test
        run: ./Executable/Windows/MyGame.exe

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4
      
      - name: Clang
        run: sudo apt update && sudo apt install -y ninja-build clang cmake

      - name: CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      
      - name: Build
        run: cmake --build build

      - name: Linux
        uses: actions/upload-artifact@v4
        with:
          name: MyGameLinux
          path: Executables/Linux

      - name: Test
        run: chmod +x ./Executable/Linux/MyGame && ./Executable/Linux/MyGame

  macos:
    runs-on: macos-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Ninja
        run: brew install ninja

      - name: CMake
        run: >
         cmake -S . -B build -G Ninja
         -DCMAKE_C_COMPILER=clang
         -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: MacOS
        uses: actions/upload-artifact@v4
        with:
          name: MyGameMacOS
          path: Executables/MacOS
       
      - name: Test
        run: chmod +x ./Executable/MacOS/MyGame && ./Executable/MacOS/MyGame