name: MyGame

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Android NDK
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk/26.3.11579264
          key: ${{ runner.os }}-android-ndk-26.3.11579264

      - name: Cache Gradle Caches & CMake FetchContent
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            Platform/Android/app/.cxx
          key: ${{ runner.os }}-android-gradle-${{ hashFiles('Platform/Android/**/*.gradle*', 'Platform/Android/**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-android-gradle-

      - name: Decode
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > Platform/Android/mygame.keystore

      - name: SDK
        uses: android-actions/setup-android@v3

      - name: Licences
        run: yes | sdkmanager --licenses

      - name: Install NDK
        run: sdkmanager "ndk;26.3.11579264"

      - name: Build
        working-directory: Platform/Android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
        env:
          STORE_FILE: ${{ github.workspace }}/Platform/Android/mygame.keystore
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Rename
        run: |
          mv Platform/Android/app/build/outputs/apk/release/app-release.apk \
          Platform/Android/app/build/outputs/apk/release/MyGame-Android-${{ github.ref_name }}.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Platform/Android/app/build/outputs/apk/release/*.apk

  windows:
    runs-on: windows-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Setup & Cache Vulkan SDK
        uses: lukka/get-vulkan-sdk@v1
        with:
          vulkan_query_version: 1.3.268.0
          enable_vulkan_sdk: true

      - name: Cache CMake Dependencies (SDL3, ENet)
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-cmake-deps-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-deps-

      - name: CMake
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Rename
        run: |
          ren Executables\Windows\MyGame.exe MyGame-Windows-${{ github.ref_name }}.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Executables\Windows\MyGame-Windows-${{ github.ref_name }}.exe

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Repo
        uses: actions/checkout@v4

      - name: Install Toolchain & Dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build clang cmake libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Setup & Cache Vulkan SDK
        uses: lukka/get-vulkan-sdk@v1
        with:
          vulkan_query_version: 1.3.268.0
          enable_vulkan_sdk: true

      - name: Cache CMake Dependencies (SDL3, ENet)
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-cmake-deps-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-deps-

      - name: CMake
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build

      - name: Rename
        run: |
          mv Executables/Linux/MyGame \
          Executables/Linux/MyGame-Linux-${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Executables/Linux/MyGame-Linux-${{ github.ref_name }}